name: Daily House Report Script Execution

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Report Script
      run: python report_script.py
      env:
        sheet_name: ${{ secrets.SHEET_NAME }}
        sheet_id: ${{ secrets.SHEET_ID }}
        app_password: ${{ secrets.APP_PASSWORD }}
        sender_email: ${{ secrets.SENDER_EMAIL }}
        recipient_mail: ${{ serets.RECIPIENT_MAIL }}